server:
  port: 8080
  servlet:
    context-path: /api

spring:
  ai:
    # 阿里灵积
    dashscope:
      api-key: ${API_KEY}
      chat:
        options:
          model: qwen-max
          parallel-tool-calls: false
      embedding:
        options:
          model: text-embedding-v4
  #    openai:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      api-key: ${API_KEY}
#      chat:
#        options:
#          model: qwen-flash-2025-07-28
##      向量模型
#      embedding:
#        options:
#          model: text-embedding-v4 # 向量模型名称

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/job_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123123
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      # 监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.job.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: 5n0XYEFAPRze+VT4YIHZpGubpwXWkhPxYoMOis1oKsbXZD6PbyscFSOBdhx8lc+LJu7nI99XSx1eVC+GeRWV/A==
  expire: 7200000  # 2小时
  header: Authorization

logging:
  level:
    com.job.mapper: debug
    org.springframework.ai: debug
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE